spring.application.name=safehome-backend

# Base de datos - Neon PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Puerto
server.port=${PORT:8080}

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method

#Sendgrid
sendgrid.api-key=${SENDGRID_API_KEY}
sendgrid.from-email=${SENDGRID_FROM_EMAIL}

#JWT
jwt.secret=${JWT_SECRET}


# Tuya Cloud API
tuya.access-id=${TUYA_ACCESS_ID:}
tuya.access-secret=${TUYA_ACCESS_SECRET:}
tuya.endpoint=${TUYA_ENDPOINT:https://openapi.tuyaus.com}
tuya.device-id=${TUYA_DEVICE_ID:}
tuya.motion-code=${TUYA_MOTION_CODE:pir_state}
tuya.motion-value=${TUYA_MOTION_VALUE:pir}
tuya.polling.enabled=${TUYA_POLLING_ENABLED:false}
tuya.polling.delay-ms=${TUYA_POLLING_DELAY_MS:1000}
tuya.motion.cooldown-ms=${TUYA_MOTION_COOLDOWN_MS:120000}

# SafeHome device/property used for Tuya sensor events
safehome.tuya.property-id=${SAFEHOME_TUYA_PROPERTY_ID:}
safehome.tuya.device-id=${SAFEHOME_TUYA_DEVICE_ID:}
safehome.tuya.latitude=${SAFEHOME_TUYA_LATITUDE:-12.0464}
safehome.tuya.longitude=${SAFEHOME_TUYA_LONGITUDE:-77.0428}



# CORS - set this in Render after Firebase gives you the public URL
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000,https://safehome-app.web.app,https://safehome-app.firebaseapp.com}
